version: v2.9.0
name: golangci-kube-api-linter
destination: ./bin
plugins:
- module: 'sigs.k8s.io/kube-api-linter'
  version: 'v0.0.0-20260206102632-39e3d06a2850' # Pin to a commit while there's no tag
