version: "2"
linters:
  default: none
  enable:
    - kubeapilinter
  settings:
    custom:
      kubeapilinter:
        type: module
        description: Kube API LInter lints Kube like APIs based on API conventions and best practices.
        settings:
          linters:
            enable:
            - "*"
            disable:
            # The linters below are disabled because they are intended to verify markers config
            # and need extra configuration
            - "conflictingmarkers"
            - "dependenttags"
            - "forbiddenmarkers"
            - "namingconventions"
            - "preferredmarkers"
            ###### The below linters need to be discussed
            - "nonpointerstructs"
          lintersConfig:
            defaults:
              preferredDefaultMarker: "kubebuilder:default"
            conditions:
              isFirstField: Warn # Require conditions to be the first field in the status struct.
              usePatchStrategy: Forbid # Forbid patchStrategy markers on the Conditions field.
              useProtobuf: Forbid # We don't use protobuf, so protobuf tags are not required.
            optionalfields:
              pointers:
                preference: WhenRequired # Always | WhenRequired # Whether to always require pointers, or only when required. Defaults to `Always`.
                policy: SuggestFix # SuggestFix | Warn # The policy for pointers in optional fields. Defaults to `SuggestFix`.
              omitempty:
                policy: SuggestFix # SuggestFix | Warn | Ignore # The policy for omitempty in optional fields. Defaults to `SuggestFix`.
  exclusions:
    generated: strict
    paths-except:
      - api/
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
run:
  timeout: 5m
  tests: false
